### ISSUE TITLE
I can't find the keystore password

### ISSUE THREAD

**Issue by RizsimStudiosOfficial** [SolsticeSpectrum/Incredibox#10]
![Screenshot 2024-10-30 170917](https://github.com/user-attachments/assets/25f560a2-1aa6-4ec0-979c-9a8a87162d6d)

**Comment by SolsticeSpectrum** [comment]
It doesn't ask for it, it wants you to make one. Just enter some password you choose and then repeat it.

**Comment by RizsimStudiosOfficial** [comment]
I can't type in it so uhhh

**Comment by RizsimStudiosOfficial** [comment]
I guess your right about it being invisible I guess nvm then I'll just close this issue now

**Comment by SolsticeSpectrum** [comment]
Btw you might want to wait until I make rewrite of this project which will be much better
