### ISSUE TITLE
Error: impossible to load language settings

### ISSUE THREAD

**Issue by IceCubeDePenguin** [SolsticeSpectrum/Incredibox#8]
when i tried launching both app.html and index.html it comes up with this error

![error](https://github.com/DarkReaper231/Incredibox/assets/125834672/8451f8bc-11bc-4ae7-a0c4-4cc1f251729b)

Do you know whyh this is happening

**Comment by DarkReaper231** [comment]
@IceCubeDePenguin You need a web server, the browser alone doesn't know where the files should be. Google: VS Code Live Server and install it to VS Code. Then open the folder containing index.html in VS Code and in bottom left corner you'll see Start Live Server or something like that. It should automatically open the url in your browser.

**Comment by IceCubeDePenguin** [comment]
thnks
