### ISSUE TITLE
Error while running command

### ISSUE THREAD

**Issue by Joalor64GH** [SolsticeSpectrum/Incredibox#9]
`brut.directory.PathNotExist: apktool.yml`

I got this error as soon as I ran the first command. What do I do?

**Comment by Joalor64GH** [comment]
Nevermind, I just found it.

**Comment by SolsticeSpectrum** [comment]
@Joalor64GH Would you mind sharing what was the issue? For future issues.

**Comment by Joalor64GH** [comment]
It was just this error I got when trying to make an Android build.
`brut.directory.PathNotExist: apktool.yml`
